with open("app/src/main/java/com/strangerhelp/app/ui/screens/tasks/PosterComponents.kt", "a") as f:
    f.write("\n\n@Composable\n")
    f.write("fun HelperProofGallery(proofImages: List<String>) {\n")
    f.write("    var selectedImage by remember { mutableStateOf<String?>(null) }\n")
    f.write("    if (proofImages.isNotEmpty()) {\n")
    f.write("        Column(verticalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {\n")
    f.write("            Text(\n")
    f.write("                text = \"📸 Submitted Proof\",\n")
    f.write("                fontWeight = FontWeight.SemiBold,\n")
    f.write("                fontSize = 14.sp\n")
    f.write("            )\n")
    f.write("            LazyRow(\n")
    f.write("                horizontalArrangement = Arrangement.spacedBy(8.dp),\n")
    f.write("                modifier = Modifier.fillMaxWidth()\n")
    f.write("            ) {\n")
    f.write("                items(proofImages) { imageUrl ->\n")
    f.write("                    coil.compose.AsyncImage(\n")
    f.write("                        model = imageUrl,\n")
    f.write("                        contentDescription = \"Proof image\",\n")
    f.write("                        modifier = Modifier\n")
    f.write("                            .size(100.dp)\n")
    f.write("                            .clip(RoundedCornerShape(8.dp))\n")
    f.write("                            .clickable { selectedImage = imageUrl },\n")
    f.write("                        contentScale = androidx.compose.ui.layout.ContentScale.Crop\n")
    f.write("                    )\n")
    f.write("                }\n")
    f.write("            }\n")
    f.write("            Text(\n")
    f.write("                text = \"Tap any image to view full screen\",\n")
    f.write("                fontSize = 11.sp,\n")
    f.write("                color = androidx.compose.ui.graphics.Color(0xFF666666)\n")
    f.write("            )\n")
    f.write("        }\n")
    f.write("    }\n")
    f.write("    selectedImage?.let { url ->\n")
    f.write("        FullScreenImageDialog(\n")
    f.write("            imageUrl = url,\n")
    f.write("            onDismiss = { selectedImage = null }\n")
    f.write("        )\n")
    f.write("    }\n")
    f.write("}\n")
